spring.application.name=ms-api-tmf632-party-mgt
spring.jackson.time-zone=America/Mexico_City
server.port=16600

# logging
logging.config=classpath:logback-spring.xml

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

#To avoid use for unknown dto params
spring.jackson.deserialization.fail-on-unknown-properties=true

#To avoid use for duplicated params
spring.jackson.parser.strict-duplicate-detection=true

    # Token WSO2
tmf632.wso2-token=wso2-token
tmf632.wso2-token.baseUrl=${CUSTOMER_BASE_URL}
tmf632.wso2-token.customerId=${CUSTOMER_USR}
tmf632.wso2-token.customerKey=${CUSTOMER_PWD}
tmf632.wso2-token.timeout.connect=5000
tmf632.wso2-token.timeout.read=10000

    # Conector CustomSCIM2 
tmf632.ciam2=ciam2
tmf632.ciam2.base-url=${SCIM2_BASE_URL}

	# Conector Prepaid (ACTIVO)
tmf632.customer-prepaid=customer-prepaid
tmf632.customer-prepaid.base-url=${PREPAID_BASE_URL}
tmf632.customer-prepaid.path=/v1/customer
tmf632.customer-prepaid.username=${PREPAID_USR}
tmf632.customer-prepaid.password=${PREPAID_PWD}

	# Conector Postpaid
tmf632.customer-postpaid=customer-postpaid
tmf632.customer-postpaid.base-url=${POSTPAID_BASE_URL}
tmf632.customer-postpaid.path=/v1/customer
tmf632.customer-postpaid.username=${POSTPAID_USR}
tmf632.customer-postpaid.password=${POSTPAID_PWD}

	# Conector tmf629-connector
tmf632.tmf629-connector=tmf629-connector
tmf632.tmf629-connector.base-url=${TMF629_BASE_URL}

	# Conector userConnector
tmf632.user-connector=user-connector
tmf632.user-connector.base-url=${USER_BASE_URL}
tmf632.user-connector.username=${USER_USER}
tmf632.user-connector.password=${USER_PWD}

# ..... DynamoDB settings......#
aws.region=${AWS_REGION}
aws.tableName=${AWS_DYNAMODB_NAME}
aws.userKey=${AWS_ACCESS_KEY_ID}
aws.passwordKey=${AWS_SECRET_ACCESS_KEY}